Develop
GeorgeII/scala-sandbox pull request #2
Opened 2021-01-07 22:00 UTC by GeorgeII

PR for the whole file HamletAverageWordLength.scala at a time.

2021-01-08 11:00 UTC, Primetalk requested changes

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +import scala.concurrent.ExecutionContext.Implicits.global
Импорт `global` допустим в тестах. В `src/main` следует использовать `(implicit ec: ExecutionContext)`. А в `main`'е создавать подходящий контекст.

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    val numberOfFutures = 6
Откуда такое число? Может, связать с `Runtime.getAvailableProcessors`?

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    // calculate every method N times and show the result of the last one. So, JVM becomes warmed up.
посмотрите  jmh (https://index.scala-lang.org/ktoso/sbt-jmh/sbt-jmh/0.3.5)

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    val source = Source.fromURL("https://raw.githubusercontent.com/benschw/shakespeare-txt/master/shakespeare-hamlet-25.txt")
Ресурсы надо закрывать...

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    // in order to create some threads in threadpool before our main task
в чём, собственно, заключается прогрев?

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    var futuresRes: (Double, Long) = (0, 0)
Ни double, ни long не являются атомарными. Их небезопасно использовать в многопоточном коде.

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +  def time[R](block: => R): (R, Long) = {
:+1:

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    } futuresRes = time {
`for {...} yield`?

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +      // this block contains the inner logic of splitting/calculating/counting with Futures.
Наличие такого комментария (this block...) подсказывает, что это отдельная функция, достойная своего имени.

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +  def findAverage(words: Seq[String]): (Double, Int) = {
1. Имя функции обманывает. Возвращается не среднее, а "полуфабрикат" для среднего.
2. find'ом обычно называют функции, которые что-то ищут в коллекции. И могут найти или не найти. sum и length - всегда возвращают результат. Например, в стандартных коллекциях есть функция `sum`, а не `findSum`.
3. Авторы последней библиотеки коллекций рекомендуют использовать конкретный тип коллекции, а не предка. Например, `Vector`

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    // remove empty strings; make "John's" -> "Johns"; trim whitespaces on both sides " Hamlet   "  -> "Hamlet".
Наличие этого комментария говорит о том, что имя функции обманывает ещё и в этом :)
Два варианта. Либо эту логику убрать из этой функции и выполнить предобработку, либо переименовать во что-то `cleanEachWordAndThenSumLengthLength`. Дальше, глядя на это имя функции, угадывается разбиение на две:
`val cleanEachWord: Vector[String] => Vector[String]`
`val sumLengthLength: Vector[String] => (Long, Long)`
которые склеены комбинатором `andThen`:
`cleanEachWord andThen sumLengthLength`

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +  def time[R](block: => R): (R, Long) = {
Хорошо бы как-то указать единицу измерения - наносекунды. Либо имя функции `timeNs`, либо `type Nanos = Long`.

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +      val sublistSize = (text.length.toDouble / numberOfFutures).ceil.toInt
Нельзя ли обойтись целочисленным делением? -1 + 1

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +      val futures = for {
Я так понимаю, это сделано для старта future?
Попробуйте `cats.effect.IO`. Там с этим проще..

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +      val (accumulatedLength, numberOfWords) = futures.map(Await.result(_, 3.second))
Вот это подрывает всю работу с Future. Await допустим либо в самом конце в main, либо в тестах.

Посмотрите `Future.traverse` и `Future.sequence`.

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +        .foldLeft((0.0, 0)) {
:+1:

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +        .foldLeft((0.0, 0)) {
Если только считать сумму (т.к. длина нам уже известна, вообще говоря), то будет несколько проще...

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    println(s"Futures                  | ${futuresRes._1} | ${futuresRes._2 / 1000000000.0} s")
`1_000 == 1000`.

2021-01-08 11:00 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    println(s"Straightforward approach | ${straightforwardRes._1} | ${straightforwardRes._2 / 1000000000.0} s")
магическая константа встречается второй раз...
Попробуйте `scala.concurrent.duration.Duration`

2021-02-08 15:29 UTC, GeorgeII commented
@Primetalk сможете посмотреть обедающих философов?

2021-02-08 15:39 UTC, Primetalk requested changes
1. Две задачи намешаны в один pull request. Должно быть две отдельные ветки и два отдельных PR.
2. Модель далека от модели обедающих философов.

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +  final case class Forks()
1. Коллекции позволяют хранить много вилок.
2. Кейс-класс без параметов можно заменить на `case object`

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +        case StartEating(forks, myName, replyTo) =>
Философ начинает есть по команде?
Мне кажется, что у философов более активная роль:
- взять правую вилку,
- подумать,
- взять левую вилку,
- подумать,
- поесть,
- положить обе вилки,
- повторить.

При таком алгоритме действий возможна ситуация, когда все философы взяли по вилке и не могут взять вторую.
В вашем варианте полностью другая модель...

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +          Thread.sleep(3 * 1000)
Для этого домашнего задания - подходит, т.к. мы эмулируем длительную работу. Вообще же `Thread.sleep` не рекомендуется.

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +            println("I am an Orchestrator and I just got 2 forks! Hmm, let me choose a philosopher to eat...")
:fearful: он хочет его съесть??

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +            val random = new Random
Класс Random нельзя создавать всякий раз. Числа при этом получатся совершенно неслучайными. Один экземпляр должен где-то хранится.

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +        val philosopher1: ActorRef[Philosopher.StartEating] = context.spawn(Philosopher(), "philosopher-1")
Получается дирижёр обзавёлся своими собственными философами...

2021-02-08 15:39 UTC, Primetalk commented on dining-philosophers-problem/src/main/scala/DiningPhilosophersProblem.scala
> +        val philosopher1: ActorRef[Philosopher.StartEating] = context.spawn(Philosopher(), "philosopher-1")
Которые только и умеют что есть...
Н-да...

2021-02-10 12:28 UTC, Primetalk approved these changes

2021-02-10 12:28 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    source.close()
В случае исключения ресурс не будет закрыт. Надо заворачивать в `try ... finally...`

2021-02-10 12:28 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    val futureSequence = Future.sequence(futures)
:+1:

2021-02-10 12:28 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    val (accumulatedLength, numberOfWords) = unwrappedSequence.foldLeft((0.0, 0L)) {
В принципе, это тоже можно было бы внутрь `Future` завернуть, чтобы `Await` уже был в самом конце.

2021-02-10 12:28 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    val futuresResult = accumulatedLength / numberOfWords
:+1:

2021-02-10 12:28 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +    cleanEachWord andThen sumLengthLength
:+1:

2021-02-10 12:28 UTC, Primetalk commented on shakespeare-words-counter/src/main/scala/HamletAverageWordLength.scala
> +  def sumLengthLength: Vector[String] => (Long, Long) = { words =>
Название загадочное...

2021-02-10 12:35 UTC, merged

2021-02-15 09:09 UTC, GeorgeII commented
@Primetalk, добрый день! 

Сделал 2 задачи. Не могли бы посмотреть? В первой возникли проблемы с Cats. Ожидал, что несколько IO будут автоматически параллелиться, но этого не происходит. Пробовал несколько разных способов, но всё безуспешно. Задачу взял свою, но по общему духу похожую на заданные. Вы, вроде, говорили, что так можно.
https://github.com/GeorgeII/scala-sandbox/pull/3

И сделал grep на akka-streams. По итогу программа совсем компактная получилась, но голову пришлось поломать. Также проверил на csv в 6 Гб -- больше, чем памяти jvm -- все работает корректно. Но, может, тоже замечания какие найдутся.
https://github.com/GeorgeII/scala-sandbox/pull/4