Grep akka streams
GeorgeII/scala-sandbox pull request #4
Opened 2021-02-14 20:32 UTC by GeorgeII

2021-02-15 09:27 UTC, Primetalk requested changes

2021-02-15 09:27 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val filename = args(1)
stdin

2021-02-15 09:27 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val source = FileIO.fromPath(Paths.get(filename), chunkSize = 1)
`chunkSize = 1` - очень маленький размер

2021-02-15 09:27 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +//      .delimiter(ByteString(System.lineSeparator()), maximumFrameLength = 512, allowTruncation = true)
Да, надо разбить поток на подходящие кусочки. Например на строки, либо на слова.

2021-02-15 09:27 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +        // start accumulating from an empty string again
Логика странная...

2021-02-15 09:27 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +        line ++ inputChunk
И накопление всего файла в памяти - не будет работать с большими файлами.

2021-02-18 11:50 UTC, Primetalk requested changes
Сложновато...

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val wordToFind = readLine()
У `grep` есть параметры командной строки..

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val filename = readLine()
Входные данные можно прекрасно читать из std in.

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def main(args: Array[String]): Unit = {
Интересно, что такое args?

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val sink = Sink.fold[String, ByteString]("") {
код организован как-то странно. Такая большая внутренняя функция?

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +        val lastString = strings(strings.length - 1)
`.last`?

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +        val firstString = previousString + strings(0)
`.head`?

2021-02-18 11:50 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +        } println(string)
побочный эффект внутри огромного `fold`'а. Может, надо разбить эту задачу на маленькие шаги?

2021-03-07 08:14 UTC, GeorgeII commented
Я не понимаю, что вы имеете в виду под "параметры командной строки". Если это не args main'а и не readLine() из StdIn, то что?)

2021-03-07 08:21 UTC, GeorgeII commented
И еще сделал TODO-лист с akka-http https://github.com/GeorgeII/scala-sandbox/pull/5. Но у вас была основа примера и некоторые вещи взял оттуда. Плюс akka-http требует достаточно строгую структуру при написании кода. Не знаю, есть ли там что проверять

2021-03-07 10:25 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def printStringsThatContainWord(strings: Vector[String], wordToFind: String): Unit = {
ERROR: Не потоковая обработка. Файл целиком загружается в память.

2021-03-07 10:25 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +      string <- strings if string.contains(wordToFind)
`.filter`?

2021-03-07 10:25 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def accumulateAndPrintLastString(lastCharInChunk: Byte, string: String, wordToFind: String): String = {
and -> or?

2021-03-07 10:25 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
>      println("Enter a word to find:")
Узнайте, что такое `args`...

2021-03-07 10:25 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +        val stringToPassToNextIteration = accumulateAndPrintLastString(inputChunk.last, lastString, wordToFind)
Что будет с самой последней строкой? Если там нет `\n`?

2021-03-07 11:58 UTC, GeorgeII commented on grep-utility/src/main/scala/Grep.scala
> +  def printStringsThatContainWord(strings: Vector[String], wordToFind: String): Unit = {
Не понимаю. У меня обрабатывается (и в самом первом коммите тоже всё обрабатывалось, я специально тестировал на файлах, превышающих объем оперативной памяти) csv 10Гб при том, что на машине оперативной памяти всего 4Гб. А у JVM, соответственно, доступной памяти и того меньше. Да и в самих док-ах пишут, что обработка идет последовательными chunk'ами длиной 8192. Метод FileIO.fromPath(Paths.get(filename)) не грузит весь файл в память (по крайней мере, я так думал, разве нет?):

https://doc.akka.io/docs/akka/current/stream/operators/FileIO/fromPath.html

https://doc.akka.io/api/akka/2.6/akka/stream/scaladsl/FileIO$.html#fromPath(f:java.nio.file.Path,chunkSize:Int,startPosition:Long):akka.stream.scaladsl.Source[akka.util.ByteString,scala.concurrent.Future[akka.stream.IOResult]]

Всё ещё не могу понять, почему это не является потоковой обработкой... Единственный краевой случай, который приходит в голову - это если файл представляет из себя одну сплошную строку, которую надо будет вывести полностью, а это уже вызовет переполнение памяти, да. Но я не уверен, что в такой ситуации и стандартный линуксовский grep справится.

2021-03-07 12:01 UTC, GeorgeII commented on grep-utility/src/main/scala/Grep.scala
>      println("Enter a word to find:")
Так я же использовал args изначально https://github.com/GeorgeII/scala-sandbox/pull/4#discussion_r576047280 
Или их надо как-то по особенному обработать? Я подумал, что обработка аргументов в этой задаче не настолько важна и предполагается, что пользователь вводит всегда корректные значения - существующие файлы и т.д.

Так что этот момент тоже не совсем понятен мне.

2021-03-07 12:11 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def printStringsThatContainWord(strings: Vector[String], wordToFind: String): Unit = {
Да, прошу прощения. Я смотрю на отдельный метод и вижу `Vector`...
Оказывается, вы сделали обработку вручную chunk'ами и vector соответствует единственному chunk'у.

Так что да, обработка поточная.

(Можно было бы не делать chunk'и самостоятельно, а воспользоваться готовым механизмом буферизации, позволяющим формировать поток строк файла...)

2021-03-07 12:11 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
>      println("Enter a word to find:")
`grep` принимает параметр - что мы ищем. А сам файл - в виде потока на stdin.

`Enter a word to find:` - интерактивное взаимодействие с пользователем. Такой способ не очень удобен в утилитах. Нет возможности автоматизировать процесс.

2021-03-07 12:11 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def printStringsThatContainWord(strings: Vector[String], wordToFind: String): Unit = {
Ну или даже самостоятельно сделать буферизацию на чанках, но не смешивать её с логикой обработки. Сформировали поток строк из файла, а дальше просто фильтруете и печатаете всё, что осталось.

2021-03-07 12:56 UTC, GeorgeII commented on grep-utility/src/main/scala/Grep.scala
> +  def accumulateAndPrintLastString(lastCharInChunk: Byte, string: String, wordToFind: String): String = {
Функция делает 2 вещи (как раз в комментарии пояснил почему так сделал): аккумулирует И печатает. Но возвращает только аккумулятор: пустую строку ИЛИ переданную изначально строку.

2021-03-07 12:57 UTC, GeorgeII commented on grep-utility/src/main/scala/Grep.scala
> +        val stringToPassToNextIteration = accumulateAndPrintLastString(inputChunk.last, lastString, wordToFind)
Печатает как ожидается, проверил на различных данных несколько раз.

2021-03-07 13:00 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def accumulateAndPrintLastString(lastCharInChunk: Byte, string: String, wordToFind: String): String = {
Можно попробовать использовать `Option[String]`. Тогда две операции можно будет разделить на две отдельные функции. Сейчас функция явно странная.

2021-03-07 13:09 UTC, GeorgeII commented
Боюсь, я не в состоянии понять, что требуется сделать с stdin :) 

Как работает grep в линуксе:
```
grep word filename.txt
```
Как сейчас работает моя программа после запуска sbt:
```
run word filename.txt
```
То есть практически полный аналог с точки зрения вызова. Что в грепе, что у меня можно указывать файлы с абсолютным путем. Stdin в грепе - это когда грепу через пайп | подается инпут с предыдущей команды? Тогда мне вообще не понятно, как в моей программе использовать пайп, если файл и так известен и дается заранее.

2021-03-07 14:19 UTC, Primetalk reviewed
`grep` также работает в режиме чтения stdin - `grep word`.

2021-03-07 14:19 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +  def printLastStringIfContains(lastCharInChunk: Byte, string: String, wordToFind: String): Unit = {
Опять мы смешиваем в одной функции несколько действий - задачу буферизации целых строк, фильтрацию и печать.

2021-03-07 14:22 UTC, Primetalk commented
Может, посмотреть в сторону `Framing` + `maximumFrameLength = <heap-size>*0.8`? Тем самым задачу буферизации мы отдадим библиотеке.

2021-03-07 17:15 UTC, Primetalk commented
Из stdin читается содержимое файла. Имя файла нам не требуется.
Из args - конфигурационные параметры, влияющие на процесс обработки. В частности, слово для фильтрации.

2021-03-09 07:07 UTC, GeorgeII commented
Попытка номер n :)

Значительно переделал структуру стрима. Source cnfk - stdin, Flow - преобразование к строке и фильтрация, Sink - println.

Теперь можно вызвать ```run word```, после чего будет считываться поток, подающийся на консоль.

2021-03-09 10:35 UTC, Primetalk approved these changes
LGTM

2021-03-09 10:35 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val source = StreamConverters.fromInputStream(() => System.in)
:+1:

2021-03-09 10:35 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    // Splits by '\n'; converts every line from bytes to string; filter strings.
:+1:

2021-03-09 10:35 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +      .filter(_.contains(wordToFind))
Yeah, a separate operation.

2021-03-09 10:35 UTC, Primetalk commented on grep-utility/src/main/scala/Grep.scala
> +    val sink = Sink.foreach(println)
the name is not very helpful..

2021-03-10 07:11 UTC, merged